name: Run code tests on push and pull requests
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: requirements.txt
          auto-activate-base: false
          channels: conda-forge
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install flake8
            python -m flake8 spec2nii
      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install pytest
            pip install .
            pytest -k "not orientation" tests
